spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 112117
    url: jdbc:mysql://47.100.180.226:3306/smsg?serverTimezone=UTC&characterEncoding=UTF8
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 9903
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql