eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: ApiDataConsumer
server:
  port: 9802
hystrix:
  metrics:
    polling-interval-ms: 5000