eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: ApiDataConsumer
  main:
    allow-bean-definition-overriding: true
server:
  port: 9801

